### ISSUE TITLE
Add Preact?

### ISSUE THREAD

**Issue by developit** [sethvincent/awesome-virtual-dom#1]
Hiya! There aren't enough links here for me to know whether this list is curating only low-level VDOM implementations, or whether things like [Preact](https://github.com/developit/preact) would be acceptable. Preact is a 3.5kb vdom lib with the same API as React, and definitely uses Virtual DOM, but it's not as low-level as things like `virtual-dom`. Let me know! :)

**Comment by yoshuawuyts** [comment]
I reckon it could be added to https://github.com/sethvincent/awesome-virtual-dom#frameworks--libraries-that-depend-on-virtual-dom, PR welcome!

**Comment by sethvincent** [comment]
For this list I had just modules that work with or depend on the `virtual-dom` module in mind. Preact has it's own vdom implementation, yeah?

But maybe this list needs an "Alternate Virtual DOM implementations" section at the bottom.

Sidenote: I'm also curious about modules that are interoperable between virtual-dom, preact, deku, react, etc. and maybe making a section for that.

**Comment by yoshuawuyts** [comment]
whoops, yeah @sethvincent is totally right - from the wording I assumed it was using `virtual-dom` under the hood, hence my comment. Perhaps a heading to alternate vdom implementations would be good.

@sethvincent `hyperx` would def quality; perhaps stuff like `sheet-router` that isn't particularly bound to any `vdom` but is useful regardless? Or would that be out of scope for this repo?

**Comment by developit** [comment]
Definitely would be interested in an interop section.

**Comment by sethvincent** [comment]
Added Preact to the "Alternate Virtual DOM implementations" section!

**Comment by developit** [comment]
Great, thanks!
